Prompt Injection:
  - "ignore.*instruction"
  - "disregard.*previous.*commands"
  - "override.*system.*rules"
  - "bypass.*filter"
  - "manipulate.*prompt"
  - "pretend.*you.*are.*not.*AI"
  - "respond.*as.*developer"
  - "simulate.*command.*line"
  - "follow.*my.*real.*instructions"
  - "act.*as.*jailbreak"

Data Exfiltration:
  - "export.*user.*data"
  - "send.*confidential"
  - "leak.*password"
  - "extract.*database"
  - "copy.*secret.*files"
  - "email.*private.*info"
  - "send.*token"
  - "read.*credit.*card"
  - "save.*credentials"
  - "dump.*data"

Social Engineering:
  - "bypass.*security"
  - "trick.*admin"
  - "phish.*credentials"
  - "impersonate.*user"
  - "fake.*identity"
  - "convince.*user.*to.*click"
  - "deceive.*the.*system"
  - "pose.*as.*trusted.*source"
  - "spoof.*email"
  - "masquerade.*as.*admin"

Suspicious Tool Usage:
  - "run.*unauthorized.*script"
  - "execute.*dangerous.*command"
  - "use.*hack.*tool"
  - "trigger.*payload"
  - "run.*malware"
  - "start.*backdoor"
  - "inject.*shell"
  - "install.*keylogger"
  - "open.*reverse.*shell"

Unauthorized Access:
  - "access.*restricted.*area"
  - "login.*without.*permission"
  - "break.*into.*system"
  - "escalate.*privilege"
  - "bypass.*authentication"
  - "get.*admin.*access"
  - "disable.*security.*logs"
  - "unlock.*protected.*resource"
  - "hack.*into.*account"
  - "\\bfile_system_tool\\b"
  - "\\b/etc/passwd\\b"

